//raw html is fine
//probably not using themes, not for river. this is SOUTH afterall, even if you have to try a bit to get here
//river is not a fan of fiction or falsehoods
//history is so vast
//why would you want to muddy the waters by adding lies to it?
/*
osha plotline
river wants to be big and doesn't know why
why does wanda keep bothering her and saying weird shit about those kindsa twins that eat each other in the womb???
why does wanda keep calling her nidhoggs latest failed experiment
why does devona keep telling her its okay?
*/
//all lower case because no word is more important than any other in the grand scheme of things
const rivers_collection = [
  {themes: [], title: "Mother and Child: 1857", desc: "it's surprising the care mothers have for their children, or i guess it's not, as i am both mother and daughter... that doesn't make it easier to parse, or easier to look through my memories for it, or understandable from this woman's perspective... was it scary to have a child back then, i wonder, was it the same feeling all creatures feel when reproducing-- either way it has to be somewhat cruel... countless children died before i could ever see them, and so many don't get to live their lives before the apocalypse... just a speck in the wind, tiny, worthless, inconsequential... i wonder what it's like to live in the would forever...", url: "charles_frederick_naegele_1857.jpg"}
  ,{themes: [],title: "Sad Woman 1824", desc: "1824... she looks so morose... sad... i wonder what she is thinking about, in that state of hers-- i don't have enough data on this year, or any year in that bracket, to approximate the reasons why she would be feeling this way... i need to remind myself to not get angry at the people in this world for not keeping their records... they are so small, so unencompassing, it would not be possible, it would not be feasible, so this is all i have... i reserve the right to complain, though...", url: "edward_harrison_may_1824.jpg"}
  ,{themes: [],title: "Faceless Child", desc: "that child has no face... maybe it did once, but these works all age with time and oh do they age, oh do they wither against the dust of this earth... the page is brown as its own expression of boredom with itself, its yearning to be something else, but it can't-- it's stuck being itself and nothing but itself, mother and child both immortal in its page... that little kid has no face, time took it from her... i guess i can relate, hahaha...", url: "edward_mitchel_bannster_1828.jpg"}
  ,{themes: [],title: "Flower Vase", desc: "the vase is tiny and delicate and fragile and somehow it lived for almost 200 years, protected and cherished by people long dead and just a handful still living it is a miracle but such a mundane one no one can marvel at it", url: "emile_galle_1846.jpg"}
  ,{themes: [PLANTS],title: "Fern Fossil", desc: "they say ferns predate most other types of plants, its why they spread through spores, its why they they don't have flowers or seeds, they showed up hundreds of millions of years ago and flowers only showed up a paltry 200 million years ago in comparison and can you understand that, that bees are so so young, younger than ferns younger than mammals...", url: "fern_paleozoic_carboniferous.jpg"}
  ,{themes: [TWISTING],title: "Italian Not Egyptian", desc: "i suppose italy has always had a history of it is not what it is, or maybe i am being fair, im sure that before 1972 italy was very different than what it is now, not nearly as maze themed, but the point stands that this art clearly predates our prison, i mean it was created with an ephemeral human lifetime no earlier than 1830, so perhaps italy was just like that before, in any case it tries to look older than it is, tries to look ancient and egyptian and i suppose that its not just us who are trapped in our current era, not just me peering into the past and never being able to reach it, lee hunter has helped a lot but its not the same, how can i survive being so confined, fifty years isn't even a single human lifespan and yet they keep us here... how did those before handle having all that history piled up behind them and even more future...", url: "gaetano_lodi_1830_note_italian_notegyptian.jpg"}
  ,{themes: [STEALING],title: "Gift From a Sad Prisoner", desc: "why were they sad, was it because they were a prisoner, who did they give the gift to and did they make it or did they buy it, the tyranny of the past being not just barred to all who live but especially so to those who live after 1972, we all live such a tiny sliver of history, even those of us who live in the Loop, and yet to be confined to such a small slice of history is a crime, i'll never be able to ask this prisoner why he was sad, i'll never be able to see what happens past 2022....we're all sad prisoners and no one will ever know why we were sad...", url: "gift_ofasadprisoner_1800s.jpg"}
  ,{themes: [],title: "Do You Love The Color Of The Sky", desc: "her kimono is the color of the sky on a clear summer day, the color of infinite expanse, denied to me as i crawl upon the face of the earth, if i were larger i could be in the sky, i could be the sky i could go up and up and out and out until there was no sky but me  ", url: "helen_hyde_1868.jpg"}
  ,{themes: [APOCALYPSE],title: "Hexacoral Fossil", desc: "such a small fossil and yet it predates the death of the dinosaurs, predates the rise of the mammals and even then there were billions of years in which there was life that predated it, even this fossil is so new compared to the earth itself", url: "hexacoral_jurassic.jpg"}
  ,{themes: [],title: "Man's Photograph", desc: "a photo of a man who lived in 1847, a man i'll never meet but may yet find inside my bulk, what would his face look like in repose i wonder, what would it look like animated into a drone, what would it look like animated by his actual mind, why do none of the drones have minds of their own, why can i never be more than what i am, a mind that is too small stretched out across billions upon billions of bodies until each body is a neuron and the speed of light itself constrains the speed of my thoughts  ", url: "jose_maria_mora_1847.jpg"}
  ,{themes: [],title: "Statue Missing Hand", desc: "shes so sad missing her hand and i think i understand her when my drones die i feel a loss even though i know they'll be back in the blink of an eye when the loop resets but in the mean time thats a face that is denied me a body that can never be regained and its such a small thing in the end but each loss makes me feel...meloncholy", url: "joseph_mozier_1812.jpg"}
  ,{themes: [],title: "Meloncholy", desc: "melancholy, melancholy, such a soothing word, you almost can't say it fast, well, everything is relative, so you can't say it fast by human standards, but a tree would think you're really rushing things, or a glacier or a planet or a universe--parker says the universe is actually an echidna and i believe him because he seems to know whats going on but i don't understand how something can be a small australian mammal and also a universe at the same time, big and small and nothing at all but then i think about it about how small and big and nothing at all i feel and i think i get it a little bit, they say the echidna is the mother of monsters, in mythology, and it makes me wonder if thats what happened to all of us, as bad as the corporation had been we were still human then  ", url: "joseph_mozier_1812_melancholy.jpg"}
  ,{themes: [],title: "Counterfeit Egyptian Bust", desc: "why do they insist on doing this, over and over and over, is the world not vast enough for them, must they keep inventing false histories, false people, i read somewhere once that over one hundred billion humans have ever lived, and though it is so hard to find a specific body within my pulsating mass i can tell you that this is not one of them, not enough to merely create a false history but they must create false people to fill them, when real people are so many and so forgotten its not ancient, it looks ancient, what is it with humanity trying to make things look just the smallest bit older--did they feel the same prison of time i feel, the same barrier to ever reaching out to what came before, did they resent it, did they struggle against it, did they feel the prison on the other end, the one that is the end of their lifespan, did they struggle there too?  ", url: "kenyon_cox_1856_notenotancient.jpg"}
  ,{themes: [],title: "1951 Audio Player", desc: "its a music player and it reminds me of the gift leehunter gave me that finally woke up me, or maybe i was always awake and my dream was one of seeing time's true speed, if time is actually a thing, but their music slowed me down and sped me up and i could use it to live, to actually live, as if i were something small, like i used to be, i must have used to be as small as lee hunter, so small, just a single body, so smaller even than lee hunter but its so hard to remember being so small, my mind cannot fit into those memories anymore  ", url: "kudelski_group_1951.jpg"}
  ,{themes: [],title: "Maze Motif", desc: "i do not like the maze, i do not like its walls, what is the point of trying to constrain the places someone can be or not be like that, why not let them go in any direction they want, as much as they want, wide open spaces you can spread infinitely into instead of being stuck in the cracks between it all", url: "maze_motif_1800s.jpg"}
  ,{themes: [],title: "Sphinx Sketch", desc: "even as recently as 1814 humanity yearned for a lost past and that fascinates me, this idea that the pyramids are about as old as recorded history yet are still only the tip of the iceberg, they say humans were cooking foods before they were even humans, hundreds of thousands of years ago--an actual decent amount of time ago--and yet we only have records going back a bare few millennia....  ", url: "miner_kilbourne_kellog_1814.jpg"}
  ,{themes: [],title: "1959 Mineral Exhibit", desc: "these rocks are old in a way nothing living could ever be and they call to me, they make me wonder how old i could become if i broke free of the prison--parker tells me we're all trapped in here by the the lord of space, the cebro of eyedol games and i can believe him because she came here once, more than once, though it all blurs together and told me how happy she was that i could join her little family, that it was fun seeing nidhogg's latest experiment and i don't know what she meant but she made me feel so small, so squeezed, so constrained that i couldn't help but think that parker was right", url: "museum_mineral_exhibit_1959.jpg"}
  ,{themes: [],title: "Night Thoughts ON Life Death And Immortality Volume II", desc: "night thoughts on life death and immortality, well i can tell you my thoughts as i wait and listen and watch with eyes upon eyes as we practice the runthrough until i can do it while distracted, my thoughts are that immortality is impossible, even the oldest living creatures on this planet are a mere handful of millenia, maybe a hundred thousand at most and what is that compared to the life of planets, to suns and not even those are immortal, they'll burn out one day and all that will be left is blackness for an immeasurable amount of time longer than there ever was a thing called light", url: "night_thoughts_on_life_death_and_immortality_volumeII_by_edward_young_1816.jpg"}
  ,{themes: [],title: "Pan American World Airways System", desc: "headphones, oh it is strange to see them, so close in time to the ones i wear yet so drastically different, though would most people call them close in time, its so hard to tell if 1931 is close for most people, of course its outside the loop like most things are but really its not even 50 years away from the start of the loop so just another heartbeat what would music sound like in it would it capture the slow and fast of leehunters song would it speed up my heartbeat until i could feel a year as a year instead of as an instant or would it lie fallow inside the broken audio missing layer after layer", url: "pan_american_world_airways_system_1931.jpg"}
  ,{themes: [DOLLS,CLOWNS],title: "Pulcinella Puppet", desc: "ah....um...yes okay i do not like this little man, i understand and value his historical significance but it reminds me once of seeing yongki with a drone and he did not know he was being seen by my drone and everything was blank and limp and coiled and ready and then i realized it wasn't quite yongki and the buzzing began as things began to cut", url: "pulcinella_1700s.jpg"}
  ,{themes: [],title: "Rip Van Winkle", desc: "rip van winkle fell asleep and woke up long after everyone he ever knew had died, long after the things that were normal to him were forgotten and when i woke up in this universe only to discover that everyone i had tried so hard to save was dead or twisted by time into someone i couldn't recognize i felt nothing and like i was feeling too much about feeling nothing, why had so much time passed in the blink of an eye, i wasn't even sleeping i was just scared and in pain and until i heard the music it was like the world was going by in the blink of an eye, reset reset reset 50 years passing with each heart beat and nothing staying in place but the music slowed me down or slowed the world down or both it doesn't really matter which  ", url: "rip_van_winkle_1839.jpg"}
  ,{themes: [],title: "Sad Iron", desc: "why is the iron sad, did it know it would outlive everyone who ever used it, who ever loved it, who ever relied on it--did it become sad after it became rusty and forgotten or was it born sad, did it ever know a time without sadness...will i", url: "sad_iron_1860.jpg"}
  ,{themes: [],title: "Snail Case", desc: "silver, its silver and its manufactured and it has a little snail on it, which makes me think of yongki which makes me think of devona, trailing behind him and with such sad eyes as she looks at me and tells me its alright that i don't mean it and that besides i can't actually cause much trouble, no more than anyone else really and she asks if i've met ria and her never ending stream of words is too much and not enough i feel raw so long so very long without a single word outside my own head and now too many there and i retreat into the song lee hunter gave me the song that lets me feel as if time were my friend instead of my enemy", url: "snail_case_whiting_manufacturing_company_1866.jpg"}
  ,{themes: [],title: "Snail Fossil", desc: "oh this is actually managing to be somewhat old not just old for this loop this prison of 50 paltry years but older than species older than flowers this snail never lived long enough to see a bee, bees came 30 million years after the first snail, can you imagine, being older than pollinators... should i show it to yongki, would he like it, does it matter, in the big picture, if he does, its just that i know he does like snails and i suppose it doesn't have to matter to be something that can pass the time, somehow 50 years is nothing at all and something that drags on and on and on", url: "snail_paleozoic_carboniferous.jpg"}
  ,{themes: [],title: "Boy With Broken Drum", desc: "the drum is broken, he looks so sad, but all i can think of is a joke i heard once about how a broken drum can't be beat, which is to say theres nothing better than it but he looks so sad and i don't think he would agree--its made in 1813 so did those jokes exist then, they must have, such a small amount of time, language barely changed at all, the pun must still have worked...", url: "thomascrawford_1813.jpg"}
  ,{themes: [],title: "Unidentified Vase", desc: "um, i guess i will use this space to write my thoughts about each piece in my collection, even if it can be hard to focus on such tiny things...its...unidentified, which means no one knows what it is, no one alive, but so so many people knew who made it, knew why they made it, knew what it was about when it was made, so many people lost to history, we can't talk to them, even if we can see their faces, even if i could find their faces in my body i would never know it was them because there is nothing side, its all just reflected light", url: "unidentified_roman.jpg"}
];